version: '3'
services:
  turtlebot3_simulator:
    image: ros2_turtlebot3
    environment:
      - DISPLAY=host.docker.internal:0
      - LIBGL_ALWAYS_INDIRECT=0
    command: bash -c "source /opt/ros/humble/setup.bash && \
                      export TURTLEBOT3_MODEL=waffle && \
                      ros2 launch turtlebot3_gazebo turtlebot3_world.launch.py"
  development:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./workspace:/root/workspace
    environment:
      - DISPLAY=host.docker.internal:0
      - LIBGL_ALWAYS_INDIRECT=0
    privileged: true
    command: bash -c "tail -F anything"
