FROM ros2_turtlebot3

# Set the working directory
WORKDIR /workspace

# Copy the source code to the container
COPY . /workspace

# Install additional dependencies, if any
# RUN /bin/bash -c "apt-get update"
# RUN /bin/bash -c "apt-get install -y <additional-packages>"

# Set environment variables, if needed
# ENV ENV_VARIABLE=value

# Run any necessary commands, e.g., build the project
RUN /bin/bash -c "source /opt/ros/humble/setup.bash && colcon build"

# Set the default command to launch the development environment
CMD ["bash"]